version: '3.8'
services:
  product-service:
    build:
      context: ./product-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/product-service

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

