version: '3.8'
services:
  product-service:
    build:
      context: ./product-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/product-service

  order-service:
    build:
      context: ./order-service
    ports:
      - "8081:8080"

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    networks:
      - app-network
    volumes:
      - ./init/mongo:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

networks:
  app-network:
    driver: bridge

